export const GET_SERVICELINE_REQUEST = "GET_SERVICELINE_REQUEST";
export const GET_SERVICELINE_SUCCESS = "GET_SERVICELINE_SUCCESS";
export const GET_SERVICELINE_FAILURE = "GET_SERVICELINE_FAILURE";




export const ADD_SERVICELINE_REQUEST = "ADD_SERVICELINE_REQUEST";
export const ADD_SERVICELINE_SUCCESS = "ADD_SERVICELINE_SUCCESS";
export const ADD_SERVICELINE_FAILURE = "ADD_SERVICELINE_FAILURE";




export const UPDATE_SERVICELINK_REQUEST = "UPDATE_SERVICELINK_REQUEST";
export const UPDATE_SERVICELINK_SUCCESS = "UPDATE_SERVICELINK_SUCCESS";
export const UPDATE_SERVICELINK_FAILURE = "UPDATE_SERVICELINK_FAILURE";




export const GET_SERVICE_LINE_COUNT_REQUEST = "GET_SERVICE_LINE_COUNT_REQUEST";
export const GET_SERVICE_LINE_COUNT_SUCCESS = "GET_SERVICE_LINE_COUNT_SUCCESS";
export const GET_SERVICE_LINE_COUNT_FAILURE = "GET_SERVICE_LINE_COUNT_FAILURE";





export const REMOVE_SERVICELINE_REQUEST = "REMOVE_SERVICELINE_REQUEST";
export const REMOVE_SERVICELINE_SUCCESS = "REMOVE_SERVICELINE_SUCCESS";
export const REMOVE_SERVICELINE_FAILURE = "REMOVE_SERVICELINE_FAILURE";