export const SET_REQUIREMENT_VIEW_TYPE="SET_REQUIREMENT_VIEW_TYPE";

export const GET_REQUIREMENT_RECORD_REQUEST="GET_REQUIREMENT_RECORD_REQUEST";
export const GET_REQUIREMENT_RECORD_SUCCESS="GET_REQUIREMENT_RECORD_SUCCESS";
export const GET_REQUIREMENT_RECORD_FAILURE="GET_REQUIREMENT_RECORD_FAILURE";

export const GET_REQUIREMENT_ORG_REQUEST="GET_REQUIREMENT_ORG_REQUEST";
export const GET_REQUIREMENT_ORG_SUCCESS="GET_REQUIREMENT_ORG_SUCCESS";
export const GET_REQUIREMENT_ORG_FAILURE="GET_REQUIREMENT_ORG_FAILURE";



export const UPDATE_RECRUITER_DATA_REQUEST =
  "UPDATE_RECRUITER_DATA_REQUEST";
export const UPDATE_RECRUITER_DATA_SUCCESS =
  "UPDATE_RECRUITER_DATA_SUCCESS";
export const UPDATE_RECRUITER_DATA_FAILURE =
  "UPDATE_RECRUITER_DATA_FAILURE";


export const HANDLE_RECRUITER_MODAL = "HANDLE_RECRUITER_MODAL";



export const LINK_CANDIDATE_RECRUIT_TO_OPPORTUNITY_REQUEST =
"LINK_CANDIDATE_RECRUIT_TO_OPPORTUNITY_REQUEST";
export const LINK_CANDIDATE_RECRUIT_TO_OPPORTUNITY_SUCCESS =
"LINK_CANDIDATE_RECRUIT_TO_OPPORTUNITY_SUCCESS";
export const LINK_CANDIDATE_RECRUIT_TO_OPPORTUNITY_FAILURE =
"LINK_CANDIDATE_RECRUIT_TO_OPPORTUNITY_FAILURE";

export const GET_ALL_REQUIREMENT_TABLE_REQUEST =
  "GET_ALL_REQUIREMENT_TABLE_REQUEST";
export const GET_ALL_REQUIREMENT_TABLE_SUCCESS=
  "GET_ALL_REQUIREMENT_TABLE_SUCCESS";
export const GET_ALL_REQUIREMENT_TABLE_FAILURE =
  "GET_ALL_REQUIREMENT_TABLE_FAILURE";

  export const HANDLE_CLAER_REDUCER_DATA_REQUIREMENT = "HANDLE_CLAER_REDUCER_DATA_REQUIREMENT";


  export const HANDLE_NWRECRUIT_MODAL = "HANDLE_NWRECRUIT_MODAL";


  export const LINK_NW_RECRUIT_TO_OPPORTUNITY_REQUEST =
  "LINK_NW_RECRUIT_TO_OPPORTUNITY_REQUEST";
export const LINK_NW_RECRUIT_TO_OPPORTUNITY_SUCCESS =
  "LINK_NW_RECRUIT_TO_OPPORTUNITY_SUCCESS";
export const LINK_NW_RECRUIT_TO_OPPORTUNITY_FAILURE =
  "LINK_NW_RECRUIT_TO_OPPORTUNITY_FAILURE";

