export const SET_INVENTORY_VIEW_TYPE = "SET_INVENTORY_VIEW_TYPE";
export const HANDLE_INVENTORY_MODAL = "HANDLE_INVENTORY_MODAL";

//add Inventory
export const ADD_INVENTORY_REQUEST = "ADD_INVENTORY_REQUEST";
export const ADD_INVENTORY_SUCCESS = "ADD_INVENTORY_SUCCESS";
export const ADD_INVENTORY_FAILURE = "ADD_INVENTORY_FAILURE";



export const LINK_DISPATCH_STATUS_REQUEST = "LINK_DISPATCH_STATUS_REQUEST";
export const LINK_DISPATCH_STATUS_SUCCESS = "LINK_DISPATCH_STATUS_SUCCESS";
export const LINK_DISPATCH_STATUS_FAILURE = "LINK_DISPATCH_STATUS_FAILURE";




export const HANDLE_RECEIVE_SCAN_MODAL = "HANDLE_RECEIVE_SCAN_MODAL";



export const ADD_SCAN_DATA_REQUEST =
  "GET_SCAN_DATA_REQUEST";
export const ADD_SCAN_DATA_SUCCESS =
  "ADD_SCAN_DATA_SUCCESS";
export const ADD_SCAN_DATA_FAILURE =
  "ADD_SCAN_DATA_FAILURE";




export const HANDLE_SCAN_MODAL = "HANDLE_SCAN_MODAL";


export const HANDLE_STOCK_MODAL = "HANDLE_STOCK_MODAL";

export const GET_MATERIAL_DAMAGE_DATA_REQUEST =
  "GET_MATERIAL_DAMAGE_DATA_REQUEST";
export const GET_MATERIAL_DAMAGE_DATA_SUCCESS =
  "GET_MATERIAL_DAMAGE_DATA_SUCCESS";
export const GET_MATERIAL_DAMAGE_DATA_FAILURE =
  "GET_MATERIAL_DAMAGE_DATA_FAILURE";

  export const GET_PACK_DATA_REQUEST =
  "GET_PACK_DATA_REQUEST";
export const GET_PACK_DATA_SUCCESS =
  "GET_PACK_DATA_SUCCESS";
export const GET_PACK_DATA_FAILURE =
  "GET_PACK_DATA_FAILURE";

  export const GET_PACK_NO_REQUEST =
  "GET_PACK_NO_REQUEST";
export const GET_PACK_NO_SUCCESS =
  "GET_PACK_NO_SUCCESS";
export const GET_PACK_NO_FAILURE =
  "GET_PACK_NO_FAILURE";

  export const GET_PACK_TRACK_REQUEST =
  "GET_PACK_TRACK_REQUEST";
export const GET_PACK_TRACK_SUCCESS =
  "GET_PACK_TRACK_SUCCESS";
export const GET_PACK_TRACK_FAILURE =
  "GET_PACK_TRACK_FAILURE";

  export const GET_SUB_LIST_REQUEST =
  "GET_SUB_LIST_REQUEST";
export const GET_SUB_LIST_SUCCESS =
  "GET_SUB_LIST_SUCCESS";
export const GET_SUB_LIST_FAILURE =
  "GET_SUB_LIST_FAILURE";

  export const GET_REPAIR_SUB_LIST_REQUEST =
  "GET_REPAIR_SUB_LIST_REQUEST";
export const GET_REPAIR_SUB_LIST_SUCCESS =
  "GET_REPAIR_SUB_LIST_SUCCESS";
export const GET_REPAIR_SUB_LIST_FAILURE =
  "GET_REPAIR_SUB_LIST_FAILURE";

export const HANDLE_INVENTORY_DISPATCH_MODAL =
  "HANDLE_INVENTORY_DISPATCH_MODAL";

export const MOVE_REJECT_TOGGLE_REQUEST = "MOVE_REJECT_TOGGLE_REQUEST";
export const MOVE_REJECT_TOGGLE_SUCCESS = "MOVE_REJECT_TOGGLE_SUCCESS";
export const MOVE_REJECT_TOGGLE_FAILURE = "MOVE_REJECT_TOGGLE_FAILURE";

export const EMPTY_QUALITY_MANUFACTURE_DATA = "EMPTY_QUALITY_MANUFACTURE_DATA";

export const GET_QUALITY_MANUFACTURE_DATA_REQUEST =
  "GET_QUALITY_MANUFACTURE_DATA_REQUEST";
export const GET_QUALITY_MANUFACTURE_DATA_SUCCESS =
  "GET_QUALITY_MANUFACTURE_DATA_SUCCESS";
export const GET_QUALITY_MANUFACTURE_DATA_FAILURE =
  "GET_QUALITY_MANUFACTURE_DATA_FAILURE";

export const HANDLE_QUALITY_MANUFACTURE_DRAWER_MODAL =
  "HANDLE_QUALITY_MANUFACTURE_DRAWER_MODAL";

export const GET_ITEM_HISTORY_DATA_IN_STOCK_REQUEST =
  "GET_ITEM_HISTORY_DATA_IN_STOCK_REQUEST";
export const GET_ITEM_HISTORY_DATA_IN_STOCK_SUCCESS =
  "GET_ITEM_HISTORY_DATA_IN_STOCK_SUCCESS";
export const GET_ITEM_HISTORY_DATA_IN_STOCK_FAILURE =
  "GET_ITEM_HISTORY_DATA_IN_STOCK_FAILURE";

export const GET_MATERIAL_UNITS_DATA_REQUEST =
  "GET_MATERIAL_UNITS_DATA_REQUEST";
export const GET_MATERIAL_UNITS_DATA_SUCCESS =
  "GET_MATERIAL_UNITS_DATA_SUCCESS";
export const GET_MATERIAL_UNITS_DATA_FAILURE =
  "GET_MATERIAL_UNITS_DATA_FAILURE";

export const GET_ARCHIEVE_PRODUCTION_BYLOC_ID_REQUEST =
  "GET_ARCHIEVE_PRODUCTION_BYLOC_ID_REQUEST";
export const GET_ARCHIEVE_PRODUCTION_BYLOC_ID_SUCCESS =
  "GET_ARCHIEVE_PRODUCTION_BYLOC_ID_SUCCESS";
export const GET_ARCHIEVE_PRODUCTION_BYLOC_ID_FAILURE =
  "GET_ARCHIEVE_PRODUCTION_BYLOC_ID_FAILURE";

export const UPDATE_ORDER_RECEIVE_REQUEST = "UPDATE_ORDER_RECEIVE_REQUEST";
export const UPDATE_ORDER_RECEIVE_SUCCESS = "UPDATE_ORDER_RECEIVE_SUCCESS";
export const UPDATE_ORDER_RECEIVE_FAILURE = "UPDATE_ORDER_RECEIVE_FAILURE";



export const ADD_SCAN_RECEIVED_DATA_REQUEST =
  "GET_SCAN_RECEIVED_DATA_REQUEST";
export const ADD_SCAN_RECEIVED_DATA_SUCCESS =
  "ADD_SCAN_RECEIVED_DATA_SUCCESS";
export const ADD_SCAN_RECEIVED_DATA_FAILURE =
  "ADD_SCAN_RECEIVED_DATA_FAILURE";

export const UPDATE_REPAIR_STATUS_REQUEST = "UPDATE_REPAIR_STATUS_REQUEST";
export const UPDATE_REPAIR_STATUS_SUCCESS = "UPDATE_REPAIR_STATUS_SUCCESS";
export const UPDATE_REPAIR_STATUS_FAILURE = "UPDATE_REPAIR_STATUS_FAILURE";

export const GET_CELL_NUMBER_REQUEST = "GET_CELL_NUMBER_REQUEST";
export const GET_CELL_NUMBER_SUCCESS = "GET_CELL_NUMBER_SUCCESS";
export const GET_CELL_NUMBER_FAILURE = "GET_CELL_NUMBER_FAILURE";

export const GET_CELL_DATA_REQUEST = "GET_CELL_DATA_REQUEST";
export const GET_CELL_DATA_SUCCESS = "GET_CELL_DATA_SUCCESS";
export const GET_CELL_DATA_FAILURE = "GET_CELL_DATA_FAILURE";

export const HANDLE_PICKUP_MODAL = "HANDLE_PICKUP_MODAL";

export const HANDLE_MISMATCH_PHONE_MODAL = "HANDLE_MISMATCH_PHONE_MODAL";

export const EMPTY_INVENTORY_LIST = "EMPTY_INVENTORY_LIST";

export const SET_INVENTORY_DETAIL_VIEW_TYPE = "SET_INVENTORY_DETAIL_VIEW_TYPE";

export const HANDLE_ADD_AWB_MODAL = "HANDLE_ADD_AWB_MODAL";

export const HANDLE_MATERIAL_RECEIVED_MODAL = "HANDLE_MATERIAL_RECEIVED_MODAL";

// get inventory

export const GET_INVENTORY_REQUEST = "GET_INVENTORY_REQUEST";
export const GET_INVENTORY_SUCCESS = "GET_INVENTORY_SUCCESS";
export const GET_INVENTORY_FAILURE = "GET_INVENTORY_FAILURE";

//inventory by id
export const GET_INVENTORY_BY_ID_REQUEST = "GET_INVENTORY_BY_ID_REQUEST";
export const GET_INVENTORY_BY_ID_SUCCESS = "GET_INVENTORY_BY_ID_SUCCESS";
export const GET_INVENTORY_BY_ID_FAILURE = "GET_INVENTORY_BY_ID_FAILURE";

//inventory outputform
export const ADD_INVENTORY_OUTPUT_REQUEST = "ADD_INVENTORY_OUTPUT_REQUEST";
export const ADD_INVENTORY_OUTPUT_SUCCESS = "ADD_INVENTORY_OUTPUT_SUCCESS";
export const ADD_INVENTORY_OUTPUT_FAILURE = "ADD_INVENTORY_OUTPUT_FAILURE";

//output table
export const GET_ALL_INVENTORY_OUTPUT_LIST_REQUEST =
  "GET_ALL_INVENTORY_OUTPUT_LIST_REQUEST";
export const GET_ALL_INVENTORY_OUTPUT_LIST_SUCCESS =
  "GET_ALL_INVENTORY_OUTPUT_LIST_SUCCESS";
export const GET_ALL_INVENTORY_OUTPUT_LIST_FAILURE =
  "GET_ALL_INVENTORY_OUTPUT_LIST_FAILURE";

//Consumption
export const GET_ALL_INVENTORY_CONSUMPTION_LIST_REQUEST =
  "GET_ALL_INVENTORY_CONSUMPTION_LIST_REQUEST";
export const GET_ALL_INVENTORY_CONSUMPTION_LIST_SUCCESS =
  "GET_ALL_INVENTORY_CONSUMPTION_LIST_SUCCESS";
export const GET_ALL_INVENTORY_CONSUMPTION_LIST_FAILURE =
  "GET_ALL_INVENTORY_CONSUMPTION_LIST_FAILURE";

export const ADD_INVENTORY_CONSUMPTION_REQUEST =
  "ADD_INVENTORY_CONSUMPTION_REQUEST";
export const ADD_INVENTORY_CONSUMPTION_SUCCESS =
  "ADD_INVENTORY_CONSUMPTION_SUCCESS";
export const ADD_INVENTORY_CONSUMPTION_FAILURE =
  "ADD_INVENTORY_CONSUMPTION_FAILURE";
//setEditInventory
export const SET_EDIT_INVENTORY = "SET_EDIT_INVENTORY";
export const HANDLE_RECEIVED_MODAL = "HANDLE_RECEIVED_MODAL";
//add received
export const ADD_RECEIVED_REQUEST = "ADD_RECEIVED_REQUEST";
export const ADD_RECEIVED_SUCCESS = "ADD_RECEIVED_SUCCESS";
export const ADD_RECEIVED_FAILURE = "ADD_RECEIVED_FAILURE";

export const HANDLE_REJECTED_REASON_MODAL = "HANDLE_REJECTED_REASON_MODAL";

export const SENT_ITEM_TO_STOCK_REQUEST = "SENT_ITEM_TO_STOCK_REQUEST";
export const SENT_ITEM_TO_STOCK_SUCCESS = "SENT_ITEM_TO_STOCK_SUCCESS";
export const SENT_ITEM_TO_STOCK_FAILURE = "SENT_ITEM_TO_STOCK_FAILURE";

export const REJECT_PHONE_REQUEST = "REJECT_PHONE_REQUEST";
export const REJECT_PHONE_SUCCESS = "REJECT_PHONE_SUCCESS";
export const REJECT_PHONE_FAILURE = "REJECT_PHONE_FAILURE";

export const REMOVE_PRODUCTION_QUALITY_REQUEST =
  "REMOVE_PRODUCTION_QUALITY_REQUEST";
export const REMOVE_PRODUCTION_QUALITY_SUCCESS =
  "REMOVE_PRODUCTION_QUALITY_SUCCESS";
export const REMOVE_PRODUCTION_QUALITY_FAILURE =
  "REMOVE_PRODUCTION_QUALITY_FAILURE";

export const LINK_MANUFACTURE_STATUS_REQUEST =
  "LINK_MANUFACTURE_STATUS_REQUEST";
export const LINK_MANUFACTURE_STATUS_SUCCESS =
  "LINK_MANUFACTURE_STATUS_SUCCESS";
export const LINK_MANUFACTURE_STATUS_FAILURE =
  "LINK_MANUFACTURE_STATUS_FAILURE";

export const UPDATE_QUALITY_STATUS_REQUEST = "UPDATE_QUALITY_STATUS_REQUEST";
export const UPDATE_QUALITY_STATUS_SUCCESS = "UPDATE_QUALITY_STATUS_SUCCESS";
export const UPDATE_QUALITY_STATUS_FAILURE = "UPDATE_QUALITY_STATUS_FAILURE";

export const GET_PRODUCTION_QUALITY_DATA_REQUEST =
  "GET_PRODUCTION_QUALITY_DATA_REQUEST";
export const GET_PRODUCTION_QUALITY_DATA_SUCCESS =
  "GET_PRODUCTION_QUALITY_DATA_SUCCESS";
export const GET_PRODUCTION_QUALITY_DATA_FAILURE =
  "GET_PRODUCTION_QUALITY_DATA_FAILURE";

export const GET_ITEM_HISTORY_IN_STOCK_REQUEST =
  "GET_ITEM_HISTORY_IN_STOCK_REQUEST";
export const GET_ITEM_HISTORY_IN_STOCK_SUCCESS =
  "GET_ITEM_HISTORY_IN_STOCK_SUCCESS";
export const GET_ITEM_HISTORY_IN_STOCK_FAILURE =
  "GET_ITEM_HISTORY_IN_STOCK_FAILURE";
//get received
export const GET_RECEIVED_REQUEST = "GET_RECEIVED_REQUEST";
export const GET_RECEIVED_SUCCESS = "GET_RECEIVED_SUCCESS";
export const GET_RECEIVED_FAILURE = "GET_RECEIVED_FAILURE";
//file damaged modal
export const HANDLE_FILE_DAMAGED_MODAL = "HANDLE_FILE_DAMAGED_MODAL";
//add Dispatch
export const ADD_DISPATCH_REQUEST = "ADD_DISPATCH_REQUEST";
export const ADD_DISPATCH_SUCCESS = "ADD_DISPATCH_SUCCESS";
export const ADD_DISPATCH_FAILURE = "ADD_DISPATCH_FAILURE";

//get dispatch
export const GET_DISPATCH_REQUEST = "GET_DISPATCH_REQUEST";
export const GET_DISPATCH_SUCCESS = "GET_DISPATCH_SUCCESS";
export const GET_DISPATCH_FAILURE = "GET_DISPATCH_FAILURE";

//checkbox
export const COMPLETE_SHIPPER_CONTACT_REQUEST =
  "COMPLETE_SHIPPER_CONTACT_REQUEST";
export const COMPLETE_SHIPPER_CONTACT_SUCCESS =
  "COMPLETE_SHIPPER_CONTACT_SUCCESS";
export const COMPLETE_SHIPPER_CONTACT_FAILURE =
  "COMPLETE_SHIPPER_CONTACT_FAILURE";
//setEditShippercontactData
export const SET_EDIT_SHIPPER_CONTACT_DATA = "SET_EDIT_SHIPPER_CONTACT_DATA";

//get dispatch List
export const GET_DISPATCH_LIST_REQUEST = "GET_DISPATCH_LIST_REQUEST";
export const GET_DISPATCH_LIST_SUCCESS = "GET_DISPATCH_LIST_SUCCESS";
export const GET_DISPATCH_LIST_FAILURE = "GET_DISPATCH_LIST_FAILURE";

export const GET_COMPLETE_DISPATCH_LIST_REQUEST = "GET_COMPLETE_DISPATCH_LIST_REQUEST";
export const GET_COMPLETE_DISPATCH_LIST_SUCCESS = "GET_COMPLETE_DISPATCH_LIST_SUCCESS";
export const GET_COMPLETE_DISPATCH_LIST_FAILURE = "GET_COMPLETE_DISPATCH_LIST_FAILURE";

export const GET_COMPLETE_DISPATCH_SEARCH_REQUEST = "GET_COMPLETE_DISPATCH_SEARCH_REQUEST";
export const GET_COMPLETE_DISPATCH_SEARCH_SUCCESS = "GET_COMPLETE_DISPATCH_SEARCH_SUCCESS";
export const GET_COMPLETE_DISPATCH_SEARCH_FAILURE = "GET_COMPLETE_DISPATCH_SEARCH_FAILURE";

export const GET_COMMERCE_LIST_REQUEST = "GET_COMMERCE_LIST_REQUEST";
export const GET_COMMERCE_LIST_SUCCESS = "GET_COMMERCE_LIST_SUCCESS";
export const GET_COMMERCE_LIST_FAILURE = "GET_COMMERCE_LIST_FAILURE";

//received details list

export const GET_RECEIVED_DETAILS_REQUEST = "GET_RECEIVED_DETAILS_REQUEST";
export const GET_RECEIVED_DETAILS_SUCCESS = "GET_RECEIVED_DETAILS_SUCCESS";
export const GET_RECEIVED_DETAILS_FAILURE = "GET_RECEIVED_DETAILS_FAILURE";
//dispatchModal
export const HANDLE_DISPTCH_MODAL = "HANDLE_DISPTCH_MODAL";
//addReceivedItem
export const ADD_TOTAL_RECEIVED_ITEM_REQUEST =
  "ADD_TOTAL_RECEIVED_ITEM_REQUEST";
export const ADD_TOTAL_RECEIVED_ITEM_SUCCESS =
  "ADD_TOTAL_RECEIVED_ITEM_SUCCESS";
export const ADD_TOTAL_RECEIVED_ITEM_FAILURE =
  "ADD_TOTAL_RECEIVED_ITEM_FAILURE";
//addDamagedItem
export const ADD_TOTAL_DAMAGED_ITEM_REQUEST = "ADD_TOTAL_DAMAGED_ITEM_REQUEST";
export const ADD_TOTAL_DAMAGED_ITEM_SUCCESS = "ADD_TOTAL_DAMAGED_ITEM_SUCCESS";
export const ADD_TOTAL_DAMAGED_ITEM_FAILURE = "ADD_TOTAL_DAMAGED_ITEM_FAILURE";

//handlePickupDateModal

export const HANDLE_PICKUP_DATE_MODAL = "HANDLE_PICKUP_DATE_MODAL";

//handleAdddispatchModal
export const HANDLE_ADD_DISPATCH_MODAL = "HANDLE_ADD_DISPATCH_MODAL";
//thirdStep
export const ADD_FINAL_DATA_IN_THIRDSTEP_REQUEST =
  "ADD_FINAL_DATA_IN_THIRDSTEP_REQUEST";
export const ADD_FINAL_DATA_IN_THIRDSTEP_SUCCESS =
  "ADD_FINAL_DATA_IN_THIRDSTEP_SUCCESS";
export const ADD_FINAL_DATA_IN_THIRDSTEP_FAILURE =
  "ADD_FINAL_DATA_IN_THIRDSTEP_FAILURE";

// outputCartIconModal
export const HANDLE_OUTPUT_REASON_MODAL = "HANDLE_OUTPUT_REASON_MODAL";
//add reason
export const ADD_REASON_REQUEST = "ADD_REASON_REQUEST";
export const ADD_REASON_SUCCESS = "ADD_REASON_SUCCESS";
export const ADD_REASON_FAILURE = "ADD_REASON_FAILURE";
export const SET_EDIT_INVENTORY_OUTPUT = "SET_EDIT_INVENTORY_OUTPUT";
//reasonList
export const GET_OUTPUT_REASON_LIST_REQUEST = "GET_OUTPUT_REASON_LIST_REQUEST";
export const GET_OUTPUT_REASON_LIST_SUCCESS = "GET_OUTPUT_REASON_LIST_SUCCESS";
export const GET_OUTPUT_REASON_LIST_FAILURE = "GET_OUTPUT_REASON_LIST_FAILURE";
//CONSUMPTION
export const HANDLE_CONSUMPTION_REASON_MODAL =
  "HANDLE_CONSUMPTION_REASON_MODAL";
//add reason
export const ADD_CONSUMPTION_REASON_REQUEST = "ADD_CONSUMPTION_REASON_REQUEST";
export const ADD_CONSUMPTION_REASON_SUCCESS = "ADD_CONSUMPTION_REASON_SUCCESS";
export const ADD_CONSUMPTION_REASON_FAILURE = "ADD_CONSUMPTION_REASON_FAILURE";
export const SET_EDIT_INVENTORY_CONSUMPTION = "SET_EDIT_INVENTORY_CONSUMPTION";
//reasonList
export const GET_CONSUMPTION_REASON_LIST_REQUEST =
  "GET_CONSUMPTION_REASON_LIST_REQUEST";
export const GET_CONSUMPTION_REASON_LIST_SUCCESS =
  "GET_CONSUMPTION_REASON_LIST_SUCCESS";
export const GET_CONSUMPTION_REASON_LIST_FAILURE =
  "GET_CONSUMPTION_REASON_LIST_FAILURE";

export const HANDLE_ADD_OUTPUT_REASON_MODAL = "HANDLE_ADD_OUTPUT_REASON_MODAL";
//outputplusReason
export const ADD_OUTPUT_PLUS_REASON_REQUEST = "ADD_OUTPUT_PLUS_REASON_REQUEST";
export const ADD_OUTPUT_PLUS_REASON_SUCCESS = "ADD_OUTPUT_PLUS_REASON_SUCCESS";
export const ADD_OUTPUT_PLUS_REASON_FAILURE = "ADD_OUTPUT_PLUS_REASON_FAILURE";
//outputplus reason list
export const GET_OUTPUT_PLUS_REASON_LIST_REQUEST =
  "GET_OUTPUT_PLUS_REASON_LIST_REQUEST";
export const GET_OUTPUT_PLUS_REASON_LIST_SUCCESS =
  "GET_OUTPUT_PLUS_REASON_LIST_SUCCESS";
export const GET_OUTPUT_PLUS_REASON_LIST_FAILURE =
  "GET_OUTPUT_PLUS_REASON_LIST_FAILURE";
export const ADD_PICKUP_DATE_REQUEST = "ADD_PICKUP_DATE_REQUEST";
export const ADD_PICKUP_DATE_SUCCESS = "ADD_PICKUP_DATE_SUCCESS";
export const ADD_PICKUP_DATE_FAILURE = "ADD_PICKUP_DATE_FAILURE";

//received delivery date

export const ADD_DELIVERY_DATE_REQUEST = "ADD_DELIVERY_DATE_REQUEST";
export const ADD_DELIVERY_DATE_SUCCESS = "ADD_DELIVERY_DATE_SUCCESS";
export const ADD_DELIVERY_DATE_FAILURE = "ADD_DELIVERY_DATE_FAILURE";

export const SET_EDIT_RECEIVED_DETAILS = "SET_EDIT_RECEIVED_DETAILS";

export const GET_SHIPPER_DETAILS_LIST_REQUEST =
  "GET_SHIPPER_DETAILS_LIST_REQUEST";
export const GET_SHIPPER_DETAILS_LIST_SUCCESS =
  "GET_SHIPPER_DETAILS_LIST_SUCCESS";
export const GET_SHIPPER_DETAILS_LIST_FAILURE =
  "GET_SHIPPER_DETAILS_LIST_FAILURE";
export const HANDLE_DELIVERY_DATE_MODAL = "HANDLE_DELIVERY_DATE_MODAL";

export const SET_EDIT_RECEIVE_INVENTORY = "SET_EDIT_RECEIVE_INVENTORY";

//updateDispatch

export const GET_DISPATCH_UPDATE_REQUEST = "GET_DISPATCH_UPDATE_REQUEST";
export const GET_DISPATCH_UPDATE_SUCCESS = "GET_DISPATCH_UPDATE_SUCCESS";
export const GET_DISPATCH_UPDATE_FAILURE = "GET_DISPATCH_UPDATE_FAILURE";
export const SET_EDIT_DISPATCH = "SET_EDIT_DISPATCH";

//reports
export const GET_INVENTORY_REPORTS_REQUEST = "GET_INVENTORY_REPORTS_REQUEST";
export const GET_INVENTORY_REPORTS_SUCCESS = "GET_INVENTORY_REPORTS_SUCCESS";
export const GET_INVENTORY_REPORTS_FAILURE = "GET_INVENTORY_REPORTS_FAILURE";

export const DELETE_DISPATCH_PRODUCT_LIST_REQUEST =
  "DELETE_DISPATCH_PRODUCT_LIST_REQUEST";
export const DELETE_DISPATCH_PRODUCT_LIST_SUCCESS =
  "DELETE_DISPATCH_PRODUCT_LIST_SUCCESS";
export const DELETE_DISPATCH_PRODUCT_LIST_FAILURE =
  "DELETE_DISPATCH_PRODUCT_LIST_FAILURE";

export const UPDATE_DISPATCH_SHIPPING_REQUEST =
  "UPDATE_DISPATCH_SHIPPING_REQUEST";
export const UPDATE_DISPATCH_SHIPPING_SUCCESS =
  "UPDATE_DISPATCH_SHIPPING_SUCCESS";
export const UPDATE_DISPATCH_SHIPPING_FAILURE =
  "UPDATE_DISPATCH_SHIPPING_FAILURE";

export const GET_DISPATCH_SHIPPER_REQUEST = "GET_DISPATCH_SHIPPER_REQUEST";
export const GET_DISPATCH_SHIPPER_SUCCESS = "GET_DISPATCH_SHIPPER_SUCCESS";
export const GET_DISPATCH_SHIPPER_FAILURE = "GET_DISPATCH_SHIPPER_FAILURE";

export const GET_INVENTORY_DISPATCH_PRODUCT_REQUEST =
  "GET_INVENTORY_DISPATCH_PRODUCT_REQUEST";
export const GET_INVENTORY_DISPATCH_PRODUCT_SUCCESS =
  "GET_INVENTORY_DISPATCH_PRODUCT_SUCCESS";
export const GET_INVENTORY_DISPATCH_PRODUCT_FAILURE =
  "GET_INVENTORY_DISPATCH_PRODUCT_FAILURE";

export const UPDATE_SHIPPER_CONTACT_REQUEST = "UPDATE_SHIPPER_CONTACT_REQUEST";
export const UPDATE_SHIPPER_CONTACT_SUCCESS = "UPDATE_SHIPPER_CONTACT_SUCCESS";
export const UPDATE_SHIPPER_CONTACT_FAILURE = "UPDATE_SHIPPER_CONTACT_FAILURE";

export const SEARCH_DISPATCH_ITEM_REQUEST = "SEARCH_DISPATCH_ITEM_REQUEST";
export const SEARCH_DISPATCH_ITEM_SUCCESS = "SEARCH_DISPATCH_ITEM_SUCCESS";
export const SEARCH_DISPATCH_ITEM_FAILURE = "SEARCH_DISPATCH_ITEM_FAILURE";

export const GET_DISPATCH_SHIPPER_UPDATE_REQUEST =
  "GET_DISPATCH_SHIPPER_UPDATE_REQUEST";
export const GET_DISPATCH_SHIPPER_UPDATE_SUCCESS =
  "GET_DISPATCH_SHIPPER_UPDATE_SUCCESS";
export const GET_DISPATCH_SHIPPER_UPDATE_FAILURE =
  "GET_DISPATCH_SHIPPER_UPDATE_FAILURE";

export const ADD_AIR_WAY_BILL_IN_SHIPPER_REQUEST =
  "ADD_AIR_WAY_BILL_IN_SHIPPER_REQUEST";
export const ADD_AIR_WAY_BILL_IN_SHIPPER_SUCCESS =
  "ADD_AIR_WAY_BILL_IN_SHIPPER_SUCCESS";
export const ADD_AIR_WAY_BILL_IN_SHIPPER_FAILURE =
  "ADD_AIR_WAY_BILL_IN_SHIPPER_FAILURE";

export const HANDLE_RECEIVED_ORDERID_MODAL = "HANDLE_RECEIVED_ORDERID_MODAL";
export const HANDLE_INVENTORY_RECEIVED_NOTE_ORDER_MODAL =
  "HANDLE_INVENTORY_RECEIVED_NOTE_ORDER_MODAL";
export const HANDLE_RECEIVED_ORDERID_PHONE_NOTE_MODAL =
  "HANDLE_RECEIVED_ORDERID_PHONE_NOTE_MODAL";

export const HANDLE_INVENTORY_ROOM_RACK_MODAL =
  "HANDLE_INVENTORY_ROOM_RACK_MODAL";

export const ADD_ROOM_AND_RACK_IN_INVENTORY_REQUEST =
  "ADD_ROOM_AND_RACK_IN_INVENTORY_REQUEST";
export const ADD_ROOM_AND_RACK_IN_INVENTORY_SUCCESS =
  "ADD_ROOM_AND_RACK_IN_INVENTORY_SUCCESS";
export const ADD_ROOM_AND_RACK_IN_INVENTORY_FAILURE =
  "ADD_ROOM_AND_RACK_IN_INVENTORY_FAILURE";

export const UPDATE_VALIDATION_IN_RECEIVE_REQUEST =
  "UPDATE_VALIDATION_IN_RECEIVE_REQUEST";
export const UPDATE_VALIDATION_IN_RECEIVE_SUCCESS =
  "UPDATE_VALIDATION_IN_RECEIVE_SUCCESS";
export const UPDATE_VALIDATION_IN_RECEIVE_FAILURE =
  "UPDATE_VALIDATION_IN_RECEIVE_FAILURE";

export const HANDLE_RECEIVE_PHONE_MODAL = "HANDLE_RECEIVE_PHONE_MODAL";

export const UPDATE_INSPECTION_REQUEST = "UPDATE_INSPECTION_REQUEST";
export const UPDATE_INSPECTION_SUCCESS = "UPDATE_INSPECTION_SUCCESS";
export const UPDATE_INSPECTION_FAILURE = "UPDATE_INSPECTION_FAILURE";

export const GET_PHONE_LIST_BY_ID_REQUEST = "GET_PHONE_LIST_BY_ID_REQUEST";
export const GET_PHONE_LIST_BY_ID_SUCCESS = "GET_PHONE_LIST_BY_ID_SUCCESS";
export const GET_PHONE_LIST_BY_ID_FAILURE = "GET_PHONE_LIST_BY_ID_FAILURE";

export const SET_PHONELIST_EDIT = "SET_PHONELIST_EDIT";

export const UPDATE_DISPATCH_INSPECTION_BUTTON_REQUEST =
  "UPDATE_DISPATCH_INSPECTION_BUTTON_REQUEST";
export const UPDATE_DISPATCH_INSPECTION_BUTTON_SUCCESS =
  "UPDATE_DISPATCH_INSPECTION_BUTTON_SUCCESS";
export const UPDATE_DISPATCH_INSPECTION_BUTTON_FAILURE =
  "UPDATE_DISPATCH_INSPECTION_BUTTON_FAILURE";

export const UPDATE_DISPATCH_RECEIVE_PHONE_REQUEST =
  "UPDATE_DISPATCH_RECEIVE_PHONE_REQUEST";
export const UPDATE_DISPATCH_RECEIVE_PHONE_SUCCESS =
  "UPDATE_DISPATCH_RECEIVE_PHONE_SUCCESS";
export const UPDATE_DISPATCH_RECEIVE_PHONE_FAILURE =
  "UPDATE_DISPATCH_RECEIVE_PHONE_FAILURE";

export const HANDLE_DISPATCH_RECEIVE_PHONE_MODAL =
  "HANDLE_DISPATCH_RECEIVE_PHONE_MODAL";

export const SET_DISPATCH_PHONELIST_EDIT = "SET_DISPATCH_PHONELIST_EDIT";

export const HANDLE_CREATE_AWB_MODAL = "HANDLE_CREATE_AWB_MODAL";

export const HANDLE_CREATE_PACK_MODAL = "HANDLE_CREATE_PACK_MODAL";

export const HANDLE_CREATE_PACK_ID = "HANDLE_CREATE_PACK_ID";

export const GET_PRODUCT_REFURBISH_REQUEST = "GET_PRODUCT_REFURBISH_REQUEST";
export const GET_PRODUCT_REFURBISH_SUCCESS = "GET_PRODUCT_REFURBISH_SUCCESS";
export const GET_PRODUCT_REFURBISH_FAILURE = "GET_PRODUCT_REFURBISH_FAILURE";

export const GET_MATERIAL_RECEIVE_DATA_REQUEST =
  "GET_MATERIAL_RECEIVE_DATA_REQUEST";
export const GET_MATERIAL_RECEIVE_DATA_SUCCESS =
  "GET_MATERIAL_RECEIVE_DATA_SUCCESS";
export const GET_MATERIAL_RECEIVE_DATA_FAILURE =
  "GET_MATERIAL_RECEIVE_DATA_FAILURE";




  export const GET_MATERIAL_BEST_BEFORE_REQUEST =
  "GET_MATERIAL_BEST_BEFORE_REQUEST";
export const GET_MATERIAL_BEST_BEFORE_SUCCESS =
  "GET_MATERIAL_BEST_BEFORE_SUCCESS";
export const GET_MATERIAL_BEST_BEFORE_FAILURE =
  "GET_MATERIAL_BEST_BEFORE_FAILURE";

  export const GET_WASTE_MATERIAL_REQUEST =
  "GET_WASTE_MATERIAL_REQUEST";
export const GET_WASTE_MATERIAL_SUCCESS =
  "GET_WASTE_MATERIAL_SUCCESS";
export const GET_WASTE_MATERIAL_FAILURE =
  "GET_WASTE_MATERIAL_FAILURE";

  export const GET_WASTE_MATERIAL_LOCATION_REQUEST =
  "GET_WASTE_MATERIAL_LOCATION_REQUEST";
export const GET_WASTE_MATERIAL_LOCATION_SUCCESS =
  "GET_WASTE_MATERIAL_LOCATION_SUCCESS";
export const GET_WASTE_MATERIAL_LOCATION_FAILURE =
  "GET_WASTE_MATERIAL_LOCATION_FAILURE";


  export const ADD_TO_WASTE_REQUEST = "ADD_TO_WASTE_REQUEST";
export const ADD_TO_WASTE_SUCCESS = "ADD_TO_WASTE_SUCCESS";
export const ADD_TO_WASTE_FAILURE = "ADD_TO_WASTE_FAILURE";



export const ADD_REPAIR_DATA_REQUEST = "ADD_REPAIR_DATA_REQUEST";
export const ADD_REPAIR_DATA_SUCCESS = "ADD_REPAIR_DATA_SUCCESS";
export const ADD_REPAIR_DATA_FAILURE = "ADD_REPAIR_DATA_FAILURE";



export const ADD_DAMAGED_CREDIT_REQUEST = "ADD_DAMAGED_CREDIT_REQUEST";
export const ADD_DAMAGED_CREDIT_SUCCESS = "ADD_DAMAGED_CREDIT_SUCCESS";
export const ADD_DAMAGED_CREDIT_FAILURE = "ADD_DAMAGED_CREDIT_FAILURE";


export const ADD_ASILE_IN_BEST_REQUEST = "ADD_ASILE_IN_BEST_REQUEST";
export const ADD_ASILE_IN_BEST_SUCCESS = "ADD_ASILE_IN_BEST_SUCCESS";
export const ADD_ASILE_IN_BEST_FAILURE = "ADD_ASILE_IN_BEST_FAILURE";


export const GET_MATERIAL_RECEIVE_DETAIL_DATA_REQUEST =
  "GET_MATERIAL_RECEIVE_DETAIL_DATA_REQUEST";
export const GET_MATERIAL_RECEIVE_DETAIL_DATA_SUCCESS =
  "GET_MATERIAL_RECEIVE_DETAIL_DATA_SUCCESS";
export const GET_MATERIAL_RECEIVE_DETAIL_DATA_FAILURE =
  "GET_MATERIAL_RECEIVE_DETAIL_DATA_FAILURE";

export const UPDATE_RECEIVED_DAMAGED_UNIT_REQUEST =
  "UPDATE_RECEIVED_DAMAGED_UNIT_REQUEST";
export const UPDATE_RECEIVED_DAMAGED_UNIT_SUCCESS =
  "UPDATE_RECEIVED_DAMAGED_UNIT_SUCCESS";
export const UPDATE_RECEIVED_DAMAGED_UNIT_FAILURE =
  "UPDATE_RECEIVED_DAMAGED_UNIT_FAILURE";

export const GENERATE_GRN_FOR_PO_REQUEST = "GENERATE_GRN_FOR_PO_REQUEST";
export const GENERATE_GRN_FOR_PO_SUCCESS = "GENERATE_GRN_FOR_PO_SUCCESS";
export const GENERATE_GRN_FOR_PO_FAILURE = "GENERATE_GRN_FOR_PO_FAILURE";

export const GET_DISPATCH_PRODUCTION_BYLOC_ID_REQUEST =
  "GET_DISPATCH_PRODUCTION_BYLOC_ID_REQUEST";
export const GET_DISPATCH_PRODUCTION_BYLOC_ID_SUCCESS =
  "GET_DISPATCH_PRODUCTION_BYLOC_ID_SUCCESS";
export const GET_DISPATCH_PRODUCTION_BYLOC_ID_FAILURE =
  "GET_DISPATCH_PRODUCTION_BYLOC_ID_FAILURE";

export const HANDLE_GRN_LIST_MODAL = "HANDLE_GRN_LIST_MODAL";

export const HANDLE_STOCK_ITEM_MODAL = "HANDLE_STOCK_ITEM_MODAL";

export const HANDLE_RECEIVED_UNIT_MODAL = "HANDLE_RECEIVED_UNIT_MODAL";

export const GET_GRN_LIST_OF_A_PO_REQUEST = "GET_GRN_LIST_OF_A_PO_REQUEST";
export const GET_GRN_LIST_OF_A_PO_SUCCESS = "GET_GRN_LIST_OF_A_PO_SUCCESS";
export const GET_GRN_LIST_OF_A_PO_FAILURE = "GET_GRN_LIST_OF_A_PO_FAILURE";

export const GET_ITEM_IN_CELL_STOCK_REQUEST = "GET_ITEM_IN_CELL_STOCK_REQUEST";
export const GET_ITEM_IN_CELL_STOCK_SUCCESS = "GET_ITEM_IN_CELL_STOCK_SUCCESS";
export const GET_ITEM_IN_CELL_STOCK_FAILURE = "GET_ITEM_IN_CELL_STOCK_FAILURE";

export const TRANSFER_PO_GRN_TO_STOCK_REQUEST =
  "TRANSFER_PO_GRN_TO_STOCK_REQUEST";
export const TRANSFER_PO_GRN_TO_STOCK_SUCCESS =
  "TRANSFER_PO_GRN_TO_STOCK_SUCCESS";
export const TRANSFER_PO_GRN_TO_STOCK_FAILURE =
  "TRANSFER_PO_GRN_TO_STOCK_FAILURE";

export const GET_RECEIVED_UNIT_OF_AN_ITEM_REQUEST =
  "GET_RECEIVED_UNIT_OF_AN_ITEM_REQUEST";
export const GET_RECEIVED_UNIT_OF_AN_ITEM_SUCCESS =
  "GET_RECEIVED_UNIT_OF_AN_ITEM_SUCCESS";
export const GET_RECEIVED_UNIT_OF_AN_ITEM_FAILURE =
  "GET_RECEIVED_UNIT_OF_AN_ITEM_FAILURE";

export const UPDATE_PART_ID_OF_AN_ITEM_REQUEST =
  "UPDATE_PART_ID_OF_AN_ITEM_REQUEST";
export const UPDATE_PART_ID_OF_AN_ITEM_SUCCESS =
  "UPDATE_PART_ID_OF_AN_ITEM_SUCCESS";
export const UPDATE_PART_ID_OF_AN_ITEM_FAILURE =
  "UPDATE_PART_ID_OF_AN_ITEM_FAILURE";

export const GET_GRN_NO_BY_PO_ID_REQUEST = "GET_GRN_NO_BY_PO_ID_REQUEST";
export const GET_GRN_NO_BY_PO_ID_SUCCESS = "GET_GRN_NO_BY_PO_ID_SUCCESS";
export const GET_GRN_NO_BY_PO_ID_FAILURE = "GET_GRN_NO_BY_PO_ID_FAILURE";

export const GET_PART_NO_BY_ITEM_REQUEST = "GET_PART_NO_BY_ITEM_REQUEST";
export const GET_PART_NO_BY_ITEM_SUCCESS = "GET_PART_NO_BY_ITEM_SUCCESS";
export const GET_PART_NO_BY_ITEM_FAILURE = "GET_PART_NO_BY_ITEM_FAILURE";

export const HANDLE_STOCK_USED_DRAWER = "HANDLE_STOCK_USED_DRAWER";

export const GET_ROOM_RACK_BY_LOCID_REQUEST = "GET_ROOM_RACK_BY_LOCID_REQUEST";
export const GET_ROOM_RACK_BY_LOCID_SUCCESS = "GET_ROOM_RACK_BY_LOCID_SUCCESS";
export const GET_ROOM_RACK_BY_LOCID_FAILURE = "GET_ROOM_RACK_BY_LOCID_FAILURE";

export const UPDATE_ROOM_RACK_ID_REQUEST = "UPDATE_ROOM_RACK_ID_REQUEST";
export const UPDATE_ROOM_RACK_ID_SUCCESS = "UPDATE_ROOM_RACK_ID_SUCCESS";
export const UPDATE_ROOM_RACK_ID_FAILURE = "UPDATE_ROOM_RACK_ID_FAILURE";

export const GET_RACK_LIST_REQUEST = "GET_RACK_LIST_REQUEST";
export const GET_RACK_LIST_SUCCESS = "GET_RACK_LIST_SUCCESS";
export const GET_RACK_LIST_FAILURE = "GET_RACK_LIST_FAILURE";

export const GET_INVENTORY_LOCATION_RECORDS_REQUEST =
  "GET_INVENTORY_LOCATION_RECORDS_REQUEST";
export const GET_INVENTORY_LOCATION_RECORDS_SUCCESS =
  "GET_INVENTORY_LOCATION_RECORDS_SUCCESS";
export const GET_INVENTORY_LOCATION_RECORDS_FAILURE =
  "GET_INVENTORY_LOCATION_RECORDS_FAILURE";

export const HANDLE_CUSTOM_MODAL = "HANDLE_CUSTOM_MODAL";

export const GET_REJECT_MANUFACTURE_DATA_REQUEST =
  "GET_REJECT_MANUFACTURE_DATA_REQUEST";
export const GET_REJECT_MANUFACTURE_DATA_SUCCESS =
  "GET_REJECT_MANUFACTURE_DATA_SUCCESS";
export const GET_REJECT_MANUFACTURE_DATA_FAILURE =
  "GET_REJECT_MANUFACTURE_DATA_FAILURE";

export const GET_QUALITY_MANUFACTURE_USER_DATA_REQUEST =
  "GET_QUALITY_MANUFACTURE_USER_DATA_REQUEST";
export const GET_QUALITY_MANUFACTURE_USER_DATA_SUCCESS =
  "GET_QUALITY_MANUFACTURE_USER_DATA_SUCCESS";
export const GET_QUALITY_MANUFACTURE_USER_DATA_FAILURE =
  "GET_QUALITY_MANUFACTURE_USER_DATA_FAILURE";

export const HANDLE_INVENTORY_EXPAND = "HANDLE_INVENTORY_EXPAND";

export const HANDLE_INVENTORY_TASK = "HANDLE_INVENTORY_TASK";

export const SEARCH_OPEN_ORDER_RECEIVED_REQUEST = "SEARCH_OPEN_ORDER_RECEIVED_REQUEST";
export const SEARCH_OPEN_ORDER_RECEIVED_SUCCESS = "SEARCH_OPEN_ORDER_RECEIVED_SUCCESS";
export const SEARCH_OPEN_ORDER_RECEIVED_FAILURE = "SEARCH_OPEN_ORDER_RECEIVED_FAILURE";

export const CLAER_REDUCERS_DATA="CLAER_REDUCERS_DATA";

export const CLAER_DISPATCH_DATA="CLAER_DISPATCH_DATA";

export const CLAER_COMPLETE_DISPATCH_DATA="CLAER_COMPLETE_DISPATCH_DATA";

export const ADD_STOCK_IMPORT_FORM_REQUEST = "ADD_STOCK_IMPORT_FORM_REQUEST";
export const ADD_STOCK_IMPORT_FORM_SUCCESS = "ADD_STOCK_IMPORT_FORM_SUCCESS";
export const ADD_STOCK_IMPORT_FORM_FAILURE = "ADD_STOCK_IMPORT_FORM_FAILURE";

export const INVENTORY_PACKED_UNPACKED_TOGGLE_REQUEST = "INVENTORY_PACKED_UNPACKED_TOGGLE_REQUEST";
export const INVENTORY_PACKED_UNPACKED_TOGGLE_SUCCESS = "INVENTORY_PACKED_UNPACKED_TOGGLE_SUCCESS";
export const INVENTORY_PACKED_UNPACKED_TOGGLE_FAILURE = "INVENTORY_PACKED_UNPACKED_TOGGLE_FAILURE";

export const LINK_MATERIAL_STOCK_TOGGLE_REQUEST =
  "LINK_MATERIAL_STOCK_TOGGLE_REQUEST";
export const LINK_MATERIAL_STOCK_TOGGLE_SUCCESS =
  "LINK_MATERIAL_STOCK_TOGGLE_SUCCESS";
export const LINK_MATERIAL_STOCK_TOGGLE_FAILURE =
  "LINK_MATERIAL_STOCK_TOGGLE_FAILURE";