export const GET_REGIONS_REQUEST = "GET_REGIONS_REQUEST";
export const GET_REGIONS_SUCCESS = "GET_REGIONS_SUCCESS";
export const GET_REGIONS_FAILURE = "GET_REGIONS_FAILURE";




export const ADD_REGIONS_REQUEST = "ADD_REGIONS_REQUEST";
export const ADD_REGIONS_SUCCESS = "ADD_REGIONS_SUCCESS";
export const ADD_REGIONS_FAILURE = "ADD_REGIONS_FAILURE";