export const GET_PROFESSIONALDUCTS_REQUEST = "GET_PROFESSIONALDUCTS_REQUEST";
export const GET_PROFESSIONALDUCTS_SUCCESS = "GET_PROFESSIONALDUCTS_SUCCESS";
export const GET_PROFESSIONALDUCTS_FAILURE = "GET_PROFESSIONALDUCTS_FAILURE";




export const HANDLE_PRODUCT_QUALITY_DRAWER="HANDLE_PRODUCT_QUALITY_DRAWER";

export const ADD_PRODUCT_BRAND_REQUEST = "ADD_PRODUCT_BRAND_REQUEST";
export const ADD_PRODUCT_BRAND_SUCCESS = "ADD_PRODUCT_BRAND_SUCCESS";
export const ADD_PRODUCT_BRAND_FAILURE = "ADD_PRODUCT_BRAND_FAILURE";




export const EMPTY_PRODUCT_LIST="EMPTY_PRODUCT_LIST";



export const UPDATE_QUALITY_PRODUCT_REQUEST = "UPDATE_QUALITY_PRODUCT_REQUEST";
export const UPDATE_QUALITY_PRODUCT_SUCCESS = "UPDATE_QUALITY_PRODUCT_SUCCESS";
export const UPDATE_QUALITY_PRODUCT_FAILURE = "UPDATE_QUALITY_PRODCUT_FAILURE";



export const DELETE_QUALITY_PRODUCT_DATA_REQUEST = "DELETE_QUALITY_PRODUCT_DATA_REQUEST";
export const DELETE_QUALITY_PRODUCT_DATA_SUCCESS = "DELETE_QUALITY_PRODUCT_DATA_SUCCESS";
export const DELETE_QUALITY_PRODUCT_DATA_FAILURE = "DELETE_QUALITY_PRODUCT_DATA_FAILURE";


export const MOVE_PRODUCT_QUALITY_REQUEST = "MOVE_PRODUCT_QUALITY_REQUEST";
export const MOVE_PRODUCT_QUALITY_SUCCESS = "MOVE_PRODUCT_QUALITY_SUCCESS";
export const MOVE_PRODUCT_QUALITY_FAILURE = "MOVE_PRODUCT_QUALITY_FAILURE";


export const ADD_DRAG_QUALITY_REQUEST = "ADD_DRAG_QUALITY_REQUEST";
export const ADD_DRAG_QUALITY_SUCCESS = "ADD_DRAG_QUALITY_SUCCESS";
export const ADD_DRAG_QUALITY_FAILURE = "ADD_DRAG_QUALITY_FAILURE";




export const GET_PRODUCTION_SPARE_DATA_REQUEST = "GET_PRODUCTION_SPARE_DATA_REQUEST";
export const GET_PRODUCTION_SPARE_DATA_SUCCESS = "GET_PRODUCTION_SPARE_DATA_SUCCESS";
export const GET_PRODUCTION_SPARE_DATA_FAILURE = "GET_PRODUCTION_SPARE_DATA_FAILURE";

export const GET_DELETEPRODUCTS_REQUEST = "GET_DELETEPRODUCTS_REQUEST";
export const GET_DELETEPRODUCTS_SUCCESS = "GET_DELETEPRODUCTS_SUCCESS";
export const GET_DELETEPRODUCTS_FAILURE = "GET_DELETEPRODUCTS_FAILURE";


export const GET_PRODUCT_DESC_REQUEST = "GET_PRODUCT_DESC_REQUEST";
export const GET_PRODUCT_DESC_SUCCESS = "GET_PRODUCT_DESC_SUCCESS";
export const GET_PRODUCT_DESC_FAILURE = "GET_PRODUCT_DESC_FAILURE";



export const ADD_PRODUCT_DESC_REQUEST = "ADD_PRODUCT_DESC_REQUEST";
export const ADD_PRODUCT_DESC_SUCCESS = "ADD_PRODUCT_DESC_SUCCESS";
export const ADD_PRODUCT_DESC_FAILURE = "ADD_PRODUCT_DESC_FAILURE";


export const GET_CATEGORY_REQUEST = "GET_CATEGORY_REQUEST";
export const GET_CATEGORY_SUCCESS = "GET_CATEGORY_SUCCESS";
export const GET_CATEGORY_FAILURE = "GET_CATEGORY_FAILURE";

export const ADD_PRODUCT_CATEGORY_REQUEST = "ADD_PRODUCT_CATEGORY_REQUEST";
export const ADD_PRODUCT_CATEGORY_SUCCESS = "ADD_PRODUCT_CATEGORY_SUCCESS";
export const ADD_PRODUCT_CATEGORY_FAILURE = "ADD_PRODUCT_CATEGORY_FAILURE";

export const GET_SERVICE_REQUEST = "GET_SERVICE_REQUEST";
export const GET_SERVICE_SUCCESS = "GET_SERVICE_SUCCESS";
export const GET_SERVICE_FAILURE = "GET_SERVICE_FAILURE";

export const GET_PRODUCT_BY_ID_REQUEST = "GET_PRODUCT_BY_ID_REQUEST";
export const GET_PRODUCT_BY_ID_SUCCESS = "GET_PRODUCT_BY_ID_SUCCESS";
export const GET_PRODUCT_BY_ID_FAILURE = "GET_PRODUCT_BY_ID_FAILURE";

export const GET_SERVICE_BY_ID_REQUEST = "GET_SERVICE_BY_ID_REQUEST";
export const GET_SERVICE_BY_ID_SUCCESS = "GET_SERVICE_BY_ID_SUCCESS";
export const GET_SERVICE_BY_ID_FAILURE = "GET_SERVICE_BY_ID_FAILURE";

export const GET_LATEST_PRODUCTS_BY_ORGANIZATION_ID_REQUEST =
  "GET_LATEST_PRODUCTS_BY_ORGANIZATION_ID_REQUEST";
export const GET_LATEST_PRODUCTS_BY_ORGANIZATION_ID_SUCCESS =
  "GET_LATEST_PRODUCTS_BY_ORGANIZATION_ID_SUCCESS";
export const GET_LATEST_PRODUCTS_BY_ORGANIZATION_ID_FAILURE =
  "GET_LATEST_PRODUCTS_BY_ORGANIZATION_ID_FAILURE";

export const ADD_SERVICE_REQUEST = "ADD_SERVICE_REQUEST";
export const ADD_SERVICE_SUCCESS = "ADD_SERVICE_SUCCESS";
export const ADD_SERVICE_FAILURE = "ADD_SERVICE_FAILURE";

export const HANDLE_PROFESSIONALDUCT_MODAL = "HANDLE_PROFESSIONALDUCT_MODAL";
export const HANDLE_SERVICE_MODAL = "HANDLE_SERVICE_MODAL";
export const HANDLE_CONFIGURE_MODAL = "HANDLE_CONFIGURE_MODAL";
export const HANDLE_DETAILSFORM_MODAL = "HANDLE_DETAILSFORM_MODAL";
export const SET_PROFESSIONALDUCT_VIEW_TYPE = "SET_PROFESSIONALDUCT_VIEW_TYPE";

export const UPDATE_SERVICE_BY_ID_REQUEST = "UPDATE_SERVICE_BY_ID_REQUEST";
export const UPDATE_SERVICE_BY_ID_SUCCESS = "UPDATE_SERVICE_BY_ID_SUCCESS";
export const UPDATE_SERVICE_BY_ID_FAILURE = "UPDATE_SERVICE_BY_ID_FAILURE";

export const UPDATE_PRODUCT_BY_ID_REQUEST = "UPDATE_PRODUCT_BY_ID_REQUEST";
export const UPDATE_PRODUCT_BY_ID_SUCCESS = "UPDATE_PRODUCT_BY_ID_SUCCESS";
export const UPDATE_PRODUCT_BY_ID_FAILURE = "UPDATE_PRODUCT_BY_ID_FAILURE";

export const CHANGE_SELECTED_TIME_INTERVAL_CATALOGUE =
  "CHANGE_SELECTED_TIME_INTERVAL_CATALOGUE";
export const SET_TIME_INTERVAL_CATALOGUE = "SET_TIME_INTERVAL_CATALOGUE";

export const HANDLE_WEIGHTED_MODAL = "HANDLE_WEIGHTED_MODAL";
export const HANDLE_ABSOLUTE_MODAL = "HANDLE_ABSOLUTE_MODAL";
export const HANDLE_WIN_MODAL = "HANDLE_WIN_MODAL";
export const HANDLE_WON_MODAL = "HANDLE_WON_MODAL";
export const HANDLE_CUSTOMER_MODAL = "HANDLE_CUSTOMER_MODAL";

export const SET_EDIT_PRODUCTS = "SET_EDIT_PRODUCTS";
export const HANDLE_UPDATE_PRODUCT_MODAL = "HANDLE_UPDATE_PRODUCT_MODAL";

export const HANDLE_CATEGORY_MODAL = "HANDLE_CATEGORY_MODAL";

export const HANDLE_DISCOUNT_BUTTON_MODAL = "HANDLE_DISCOUNT_BUTTON_MODAL";

export const GET_DISCOUNT_HISTORY_REQUEST = "GET_DISCOUNT_HISTORY_REQUEST";
export const GET_DISCOUNT_HISTORY_SUCCESS = "GET_DISCOUNT_HISTORY_SUCCESS";
export const GET_DISCOUNT_HISTORY_FAILURE = "GET_DISCOUNT_HISTORY_FAILURE";

export const ADD_DISCOUNT_REQUEST = "ADD_DISCOUNT_REQUEST";
export const ADD_DISCOUNT_SUCCESS = "ADD_DISCOUNT_SUCCESS";
export const ADD_DISCOUNT_FAILURE = "ADD_DISCOUNT_FAILURE";

export const HANDLE_PRODUCT_HISTORY_MODAL = "HANDLE_PRODUCT_HISTORY_MODAL";

export const GET_PRODUCT_HISTORY_REQUEST = "GET_PRODUCT_HISTORY_REQUEST";
export const GET_PRODUCT_HISTORY_SUCCESS = "GET_PRODUCT_HISTORY_SUCCESS";
export const GET_PRODUCT_HISTORY_FAILURE = "GET_PRODUCT_HISTORY_FAILURE";

//suspend prduct
export const SUSPEND_PRODUCT_REQUEST = "SUSPEND_PRODUCT_REQUEST";
export const SUSPEND_PRODUCT_SUCCESS = "SUSPEND_PRODUCT_SUCCESS";
export const SUSPEND_PRODUCT_FAILURE = "SUSPEND_PRODUCT_FAILURE";

export const DELETE_PRODUCT_DATA_REQUEST = "DELETE_PRODUCT_DATA_REQUEST";
export const DELETE_PRODUCT_DATA_SUCCESS = "DELETE_PRODUCT_DATA_SUCCESS";
export const DELETE_PRODUCT_DATA_FAILURE = "DELETE_PRODUCT_DATA_FAILURE";

export const DELETE_CATALOG_DATA_REQUEST = "DELETE_CATALOG_DATA_REQUEST";
export const DELETE_CATALOG_DATA_SUCCESS = "DELETE_CATALOG_DATA_SUCCESS";
export const DELETE_CATALOG_DATA_FAILURE = "DELETE_CATALOG_DATA_FAILURE";

export const GET_SUSPEND_PRODUCT_REQUEST = "GET_SUSPEND_PRODUCT_REQUEST";
export const GET_SUSPEND_PRODUCT_SUCCESS = "GET_SUSPEND_PRODUCT_SUCCESS";
export const GET_SUSPEND_PRODUCT_FAILURE = "GET_SUSPEND_PRODUCT_FAILURE";

//configure
export const HANDLE_CATALOGUE_CONFIGURE_MODAL =
  "HANDLE_CATALOGUE_CONFIGURE_MODAL";
//add configure
export const ADD_CATALOGUE_CONFIGURE_REQUEST =
  "ADD_CATALOGUE_CONFIGURE_REQUEST";
export const ADD_CATALOGUE_CONFIGURE_SUCCESS =
  "ADD_CATALOGUE_CONFIGURE_SUCCESS";
export const ADD_CATALOGUE_CONFIGURE_FAILURE =
  "ADD_CATALOGUE_CONFIGURE_FAILURE";

//get configure list
export const GET_CATALOGUE_CONFIGURE_LIST_REQUEST =
  "GET_CATALOGUE_CONFIGURE_LIST_REQUEST";
export const GET_CATALOGUE_CONFIGURE_LIST_SUCCESS =
  "GET_CATALOGUE_CONFIGURE_LIST_SUCCESS";
export const GET_CATALOGUE_CONFIGURE_LIST_FAILURE =
  "GET_CATALOGUE_CONFIGURE_LIST_FAILURE";

export const ADD_DISCOUNT_DISTRIBUTOR_REQUEST =
  "ADD_DISCOUNT_DISTRIBUTOR_REQUEST";
export const ADD_DISCOUNT_DISTRIBUTOR_SUCCESS =
  "ADD_DISCOUNT_DISTRIBUTOR_SUCCESS";
export const ADD_DISCOUNT_DISTRIBUTOR_FAILURE =
  "ADD_DISCOUNT_DISTRIBUTOR_FAILURE";

export const GET_DISTRIBUTOR_DISCOUNT_HISTORY_REQUEST =
  "GET_DISTRIBUTOR_DISCOUNT_HISTORY_REQUEST";
export const GET_DISTRIBUTOR_DISCOUNT_HISTORY_SUCCESS =
  "GET_DISTRIBUTOR_DISCOUNT_HISTORY_SUCCESS";
export const GET_DISTRIBUTOR_DISCOUNT_HISTORY_FAILURE =
  "GET_DISTRIBUTOR_DISCOUNT_HISTORY_FAILURE";


export const GET_RECORDS_REQUEST = "GET_RECORDS_REQUEST";
export const GET_RECORDS_SUCCESS = "GET_RECORDS_SUCCESS";
export const GET_RECORDS_FAILURE = "GET_RECORDS_FAILURE";

export const GET_DELETED_PRODUCT_RECORDS_REQUEST = "GET_DELETED_PRODUCT_RECORDS_REQUEST";
export const GET_DELETED_PRODUCT_RECORDS_SUCCESS = "GET_DELETED_PRODUCT_RECORDS_SUCCESS";
export const GET_DELETED_PRODUCT_RECORDS_FAILURE = "GET_DELETED_PRODUCT_RECORDS_FAILURE";

export const GET_ALL_PRODUCT_REQUEST = "GET_ALL_PRODUCT_REQUEST";
export const GET_ALL_PRODUCT_SUCCESS = "GET_ALL_PRODUCT_SUCCESS";
export const GET_ALL_PRODUCT_FAILURE = "GET_ALL_PRODUCT_FAILURE";

export const HANDLE_OFFER_BUTTON_MODAL = "HANDLE_OFFER_BUTTON_MODAL";

export const ADD_CUSTOMER_OFFER_REQUEST = "ADD_CUSTOMER_OFFER_REQUEST";
export const ADD_CUSTOMER_OFFER_SUCCESS = "ADD_CUSTOMER_OFFER_SUCCESS";
export const ADD_CUSTOMER_OFFER_FAILURE = "ADD_CUSTOMER_OFFER_FAILURE";

export const ADD_DISTRIBUTOR_OFFER_REQUEST = "ADD_DISTRIBUTOR_OFFER_REQUEST";
export const ADD_DISTRIBUTOR_OFFER_SUCCESS = "ADD_DISTRIBUTOR_OFFER_SUCCESS";
export const ADD_DISTRIBUTOR_OFFER_FAILURE = "ADD_DISTRIBUTOR_OFFER_FAILURE";

export const GET_CUSTOMER_OFFER_HISTORY_REQUEST = "GET_CUSTOMER_OFFER_HISTORY_REQUEST";
export const GET_CUSTOMER_OFFER_HISTORY_SUCCESS = "GET_CUSTOMER_OFFER_HISTORY_SUCCESS";
export const GET_CUSTOMER_OFFER_HISTORY_FAILURE = "GET_CUSTOMER_OFFER_HISTORY_FAILURE";

export const GET_DISTRIBUTOR_OFFER_HISTORY_REQUEST = "GET_DISTRIBUTOR_OFFER_HISTORY_REQUEST";
export const GET_DISTRIBUTOR_OFFER_HISTORY_SUCCESS = "GET_DISTRIBUTOR_OFFER_HISTORY_SUCCESS";
export const GET_DISTRIBUTOR_OFFER_HISTORY_FAILURE = "GET_DISTRIBUTOR_OFFER_HISTORY_FAILURE";

export const SET_CLEARBIT_PRODUCT_DATA = "SET_CLEARBIT_PRODUCT_DATA";

export const HANDLE_UPDATE_CUSTOMER_OFFER_MODAL = "HANDLE_UPDATE_CUSTOMER_OFFER_MODAL";
export const SET_EDIT_CUSTOMER_OFFER = "SET_EDIT_CUSTOMER_OFFER";

export const HANDLE_UPDATE_DISTRIBUTOR_OFFER_MODAL = "HANDLE_UPDATE_DISTRIBUTOR_OFFER_MODAL";
export const SET_EDIT_DISTRIBUTOR_OFFER = "SET_EDIT_DISTRIBUTOR_OFFER";

export const SET_CLEARBIT_PRODUCT_DISTRIBUTOR_DATA = "SET_CLEARBIT_PRODUCT_DISTRIBUTOR_DATA";

export const UPDATE_CUSTOMER_OFFER_REQUEST = "UPDATE_CUSTOMER_OFFER_REQUEST";
export const UPDATE_CUSTOMER_OFFER_SUCCESS = "UPDATE_CUSTOMER_OFFER_SUCCESS";
export const UPDATE_CUSTOMER_OFFER_FAILURE = "UPDATE_CUSTOMER_OFFER_FAILURE";

export const UPDATE_DISTRIBUTOR_OFFER_REQUEST = "UPDATE_DISTRIBUTOR_OFFER_REQUEST";
export const UPDATE_DISTRIBUTOR_OFFER_SUCCESS = "UPDATE_DISTRIBUTOR_OFFER_SUCCESS";
export const UPDATE_DISTRIBUTOR_OFFER_FAILURE = "UPDATE_DISTRIBUTOR_OFFER_FAILURE";

export const HANDLE_CATALOGUE_WIP_MODAL = "HANDLE_CATALOGUE_WIP_MODAL";
export const HANDLE_CATEGORYIMAGE_MODAL = "HANDLE_CATEGORYIMAGE_MODAL";

export const ADD_CATEGORY_IMAGE_REQUEST = "ADD_CATEGORY_IMAGE_REQUEST";
export const ADD_CATEGORY_IMAGE_SUCCESS = "ADD_CATEGORY_IMAGE_SUCCESS";
export const ADD_CATEGORY_IMAGE_FAILURE = "ADD_CATEGORY_IMAGE_FAILURE";

export const GET_CATEGORY_IMAGE_REQUEST = "GET_CATEGORY_IMAGE_REQUEST";
export const GET_CATEGORY_IMAGE_SUCCESS = "GET_CATEGORY_IMAGE_SUCCESS";
export const GET_CATEGORY_IMAGE_FAILURE = "GET_CATEGORY_IMAGE_FAILURE";

export const PRODUCT_PUBLISH_TOGGLE_REQUEST = "PRODUCT_PUBLISH_TOGGLE_REQUEST";
export const PRODUCT_PUBLISH_TOGGLE_SUCCESS = "PRODUCT_PUBLISH_TOGGLE_SUCCESS";
export const PRODUCT_PUBLISH_TOGGLE_FAILURE = "PRODUCT_PUBLISH_TOGGLE_FAILURE";

export const GET_PRODUCT_BY_GROUP_REQUEST = "GET_PRODUCT_BY_GROUP_REQUEST";
export const GET_PRODUCT_BY_GROUP_SUCCESS = "GET_PRODUCT_BY_GROUP_SUCCESS";
export const GET_PRODUCT_BY_GROUP_FAILURE = "GET_PRODUCT_BY_GROUP_FAILURE";

export const ADD_TO_MATERIAL_REQUEST = "ADD_TO_MATERIAL_REQUEST";
export const ADD_TO_MATERIAL_SUCCESS = "ADD_TO_MATERIAL_SUCCESS";
export const ADD_TO_MATERIAL_FAILURE = "ADD_TO_MATERIAL_FAILURE";

export const HANDLE_UPLOAD_PRODUCT_MODAL = "HANDLE_UPLOAD_PRODUCT_MODAL";

export const UPLOAD_PRODUCT_LISTS_REQUEST = "UPLOAD_PRODUCT_LISTS_REQUEST";
export const UPLOAD_PRODUCT_LISTS_SUCCESS = "UPLOAD_PRODUCT_LISTS_SUCCESS";
export const UPLOAD_PRODUCT_LISTS_FAILURE = "UPLOAD_PRODUCT_LISTS_FAILURE";



export const HANDLE_PRODUCT_BRAND_MODAL = "HANDLE_PRODUCT_BRAND_MODAL";



export const GET_BRAND_PRODUCT_REQUEST = "GET_BRAND_PRODUCT_REQUEST";
export const GET_BRAND_PRODUCT_SUCCESS = "GET_BRAND_PRODUCT_SUCCESS";
export const GET_BRAND_PRODUCT_FAILURE = "GET_BRAND_PRODUCT_FAILURE";

export const ADD_PROFESSIONALDUCT_REQUEST = "ADD_PROFESSIONALDUCT_REQUEST";
export const ADD_PROFESSIONALDUCT_SUCCESS = "ADD_PROFESSIONALDUCT_SUCCESS";
export const ADD_PROFESSIONALDUCT_FAILURE = "ADD_PROFESSIONALDUCT_FAILURE";

export const ADD_CATEGORY_REQUEST = "ADD_CATEGORY_REQUEST";
export const ADD_CATEGORY_SUCCESS = "ADD_CATEGORY_SUCCESS";
export const ADD_CATEGORY_FAILURE = "ADD_CATEGORY_FAILURE";

export const HANDLE_PRODUCT_BUILDER_DRAWER = "HANDLE_PRODUCT_BUILDER_DRAWER";

export const GET_PRODUCT_BUILDER_REQUEST = "GET_PRODUCT_BUILDER_REQUEST";
export const GET_PRODUCT_BUILDER_SUCCESS = "GET_PRODUCT_BUILDER_SUCCESS";
export const GET_PRODUCT_BUILDER_FAILURE = "GET_PRODUCT_BUILDER_FAILURE";

export const ADD_PRODUCT_BUILDER_REQUEST = "ADD_PRODUCT_BUILDER_REQUEST";
export const ADD_PRODUCT_BUILDER_SUCCESS = "ADD_PRODUCT_BUILDER_SUCCESS";
export const ADD_PRODUCT_BUILDER_FAILURE = "ADD_PRODUCT_BUILDER_FAILURE";

export const GET_BUILDER_BY_PRODUCT_ID_REQUEST = "GET_BUILDER_BY_PRODUCT_ID_REQUEST";
export const GET_BUILDER_BY_PRODUCT_ID_SUCCESS = "GET_BUILDER_BY_PRODUCT_ID_SUCCESS";
export const GET_BUILDER_BY_PRODUCT_ID_FAILURE = "GET_BUILDER_BY_PRODUCT_ID_FAILURE";

export const HANDLE_PRICE_DRAWER = 'HANDLE_PRICE_DRAWER';

export const UPLOAD_CATALOGUE_LIST_REQUEST = "UPLOAD_CATALOGUE_LIST_REQUEST";
export const UPLOAD_CATALOGUE_LIST_SUCCESS = "UPLOAD_CATALOGUE_LIST_SUCCESS";
export const UPLOAD_CATALOGUE_LIST_FAILURE = "UPLOAD_CATALOGUE_LIST_FAILURE";

export const REMOVE_PRODUCT_BUILDER_REQUEST = "REMOVE_PRODUCT_BUILDER_REQUEST";
export const REMOVE_PRODUCT_BUILDER_SUCCESS = "REMOVE_PRODUCT_BUILDER_SUCCESS";
export const REMOVE_PRODUCT_BUILDER_FAILURE = "REMOVE_PRODUCT_BUILDER_FAILURE";

export const UPDATE_PRO_SUPPL_BUILDER_REQUEST = "UPDATE_PRO_SUPPL_BUILDER_REQUEST";
export const UPDATE_PRO_SUPPL_BUILDER_SUCCESS = "UPDATE_PRO_SUPPL_BUILDER_SUCCESS";
export const UPDATE_PRO_SUPPL_BUILDER_FAILURE = "UPDATE_PRO_SUPPL_BUILDER_FAILURE";

export const GET_PRODUCT_CURRENCY_REQUEST = "GET_PRODUCT_CURRENCY_REQUEST";
export const GET_PRODUCT_CURRENCY_SUCCESS = "GET_PRODUCT_CURRENCY_SUCCESS";
export const GET_PRODUCT_CURRENCY_FAILURE = "GET_PRODUCT_CURRENCY_FAILURE";
export const CREATE_PRODUCT_CURRENCY_REQUEST = "CREATE_PRODUCT_CURRENCY_REQUEST";
export const CREATE_PRODUCT_CURRENCY_SUCCESS = "CREATE_PRODUCT_CURRENCY_SUCCESS";
export const CREATE_PRODUCT_CURRENCY_FAILURE = "CREATE_PRODUCT_CURRENCY_FAILURE";

export const GET_SEARCH_BUILDER_REQUEST = "GET_SEARCH_BUILDER_REQUEST";
export const GET_SEARCH_BUILDER_SUCCESS = "GET_SEARCH_BUILDER_SUCCESS";
export const GET_SEARCH_BUILDER_FAILURE = "GET_SEARCH_BUILDER_FAILURE";

export const GET_ALL_PRODUCT_LIST_REQUEST="GET_ALL_PRODUCT_LIST_REQUEST";
export const GET_ALL_PRODUCT_LIST_SUCCESS="GET_ALL_PRODUCT_LIST_SUCCESS";
export const GET_ALL_PRODUCT_LIST_FAILURE="GET_ALL_PRODUCT_LIST_FAILURE";

export const POST_PRODUCTION_BUILDER_REQUEST = "POST_PRODUCTION_BUILDER_REQUEST";
export const POST_PRODUCTION_BUILDER_SUCCESS = "POST_PRODUCTION_BUILDER_SUCCESS";
export const POST_PRODUCTION_BUILDER_FAILURE = "POST_PRODUCTION_BUILDER_FAILURE";

export const HANDLE_PRODUCT_CELL_DRAWER="HANDLE_PRODUCT_CELL_DRAWER";


export const GET_QUALITY_PRODUCTS_REQUEST = "GET_QUALITY_PRODUCTS_REQUEST";
export const GET_QUALITY_PRODUCTS_SUCCESS = "GET_QUALITY_PRODUCTS_SUCCESS";
export const GET_QUALITY_PRODUCTS_FAILURE = "GET_QUALITY_PRODUCTS_FAILURE";


export const CREATE_QUALITY_PRODUCT_REQUEST = "CREATE_QUALITY_PRODUCT_REQUEST";
export const CREATE_QUALITY_PRODUCT_SUCCESS = "CREATE_QUALITY_PRODUCT_SUCCESS";
export const CREATE_QUALITY_PRODUCT_FAILURE = "CREATE_QUALITY_PRODUCT_FAILURE";

export const UPDATE_PROD_SUPPLR_BILDR_REQUEST = "UPDATE_PROD_SUPPLR_BILDR_REQUEST";
export const UPDATE_PROD_SUPPLR_BILDR_SUCCESS = "UPDATE_PROD_SUPPLR_BILDR_SUCCESS";
export const UPDATE_PROD_SUPPLR_BILDR_FAILURE = "UPDATE_PROD_SUPPLR_BILDR_FAILURE";

export const REMOVE_PRODUCT_PRICE_REQUEST = "REMOVE_PRODUCT_PRICE_REQUEST";
export const REMOVE_PRODUCT_PRICE_SUCCESS = "REMOVE_PRODUCT_PRICE_SUCCESS";
export const REMOVE_PRODUCT_PRICE_FAILURE = "REMOVE_PRODUCT_PRICE_FAILURE";

export const HANDLE_PRODUCT_NOTES_DRAWER_MODAL = "HANDLE_PRODUCT_NOTES_DRAWER_MODAL";

// export const REINSTATE_DELETED_PRODUCTS_REQUEST = "REINSTATE_DELETED_PRODUCTS_REQUEST";
// export const REINSTATE_DELETED_PRODUCTS_SUCCESS = "REINSTATE_DELETED_PRODUCTS_SUCCESS";
// export const REINSTATE_DELETED_PRODUCTS_FAILURE = "REINSTATE_DELETED_PRODUCTS_FAILURE";

export const GET_NOTES_OF_PRODUCT_REQUEST = "GET_NOTES_OF_PRODUCT_REQUEST";
export const GET_NOTES_OF_PRODUCT_SUCCESS = "GET_NOTES_OF_PRODUCT_SUCCESS";
export const GET_NOTES_OF_PRODUCT_FAILURE = "GET_NOTES_OF_PRODUCT_FAILURE";
export const ADD_NOTES_OF_PRODUCT_REQUEST = "ADD_NOTES_OF_PRODUCT_REQUEST";
export const ADD_NOTES_OF_PRODUCT_SUCCESS = "ADD_NOTES_OF_PRODUCT_SUCCESS";
export const ADD_NOTES_OF_PRODUCT_FAILURE = "ADD_NOTES_OF_PRODUCT_FAILURE";
export const UPDATE_NOTES_OF_PRODUCT_REQUEST = "UPDATE_NOTES_OF_PRODUCT_REQUEST";
export const UPDATE_NOTES_OF_PRODUCT_SUCCESS = "UPDATE_NOTES_OF_PRODUCT_SUCCESS";
export const UPDATE_NOTES_OF_PRODUCT_FAILURE = "UPDATE_NOTES_OF_PRODUCT_FAILURE";
export const REMOVE_NOTES_OF_PRODUCT_REQUEST = "REMOVE_NOTES_OF_PRODUCT_REQUEST";
export const REMOVE_NOTES_OF_PRODUCT_SUCCESS = "REMOVE_NOTES_OF_PRODUCT_SUCCESS";
export const REMOVE_NOTES_OF_PRODUCT_FAILURE = "REMOVE_NOTES_OF_PRODUCT_FAILURE";

export const GET_PRODUCT_HSN_REQUEST = "GET_PRODUCT_HSN_REQUEST";
export const GET_PRODUCT_HSN_SUCCESS = "GET_PRODUCT_HSN_SUCCESS";
export const GET_PRODUCT_HSN_FAILURE = "GET_PRODUCT_HSN_FAILURE";

export const FEATURED_PRODUCT_TOGGLE_REQUEST = "FEATURED_PRODUCT_TOGGLE_REQUEST";
export const FEATURED_PRODUCT_TOGGLE_SUCCESS = "FEATURED_PRODUCT_TOGGLE_SUCCESS";
export const FEATURED_PRODUCT_TOGGLE_FAILURE = "FEATURED_PRODUCT_TOGGLE_FAILURE";

export const CATALOGUE_CATEGORY_SEARCH_REQUEST = "CATALOGUE_CATEGORY_SEARCH_REQUEST";
export const CATALOGUE_CATEGORY_SEARCH_SUCCESS = "CATALOGUE_CATEGORY_SEARCH_SUCCESS";
export const CATALOGUE_CATEGORY_SEARCH_FAILURE = "CATALOGUE_CATEGORY_SEARCH_FAILURE";

export const GET_PRODUCTS_BY_PRODUCTID_REQUEST = "GET_PRODUCTS_BY_PRODUCTID_REQUEST";
export const GET_PRODUCTS_BY_PRODUCTID_SUCCESS = "GET_PRODUCTS_BY_PRODUCTID_SUCCESS";
export const GET_PRODUCTS_BY_PRODUCTID_FAILURE = "GET_PRODUCTS_BY_PRODUCTID_FAILURE";

export const PRODUCT_PUNBLISH_TOGGLE_REQUEST = "PRODUCT_PUNBLISH_TOGGLE_REQUEST";
export const PRODUCT_PUNBLISH_TOGGLE_SUCCESS = "PRODUCT_PUNBLISH_TOGGLE_SUCCESS";
export const PRODUCT_PUNBLISH_TOGGLE_FAILURE = "PRODUCT_PUNBLISH_TOGGLE_FAILURE";

export const WARRENTY_PRODUCT_TOGGLE_REQUEST = "WARRENTY_PRODUCT_TOGGLE_REQUEST";
export const WARRENTY_PRODUCT_TOGGLE_SUCCESS = "WARRENTY_PRODUCT_TOGGLE_SUCCESS";
export const WARRENTY_PRODUCT_TOGGLE_FAILURE = "WARRENTY_PRODUCT_TOGGLE_FAILURE";

export const UPDATE_DATE_YEAR_PRODUCT_REQUEST = "UPDATE_DATE_YEAR_PRODUCT_REQUEST";
export const UPDATE_DATE_YEAR_PRODUCT_SUCCESS = "UPDATE_DATE_YEAR_PRODUCT_SUCCESS";
export const UPDATE_DATE_YEAR_PRODUCT_FAILURE = "UPDATE_DATE_YEAR_PRODUCT_FAILURE"

