export const SET_PROCRE_VIEW_TYPE = "SET_PROCRE_VIEW_TYPE";

export const GET_ALL_PROCURE_REQUEST = "GET_ALL_PROCURE_REQUEST";
export const GET_ALL_PROCURE_SUCCESS = "GET_ALL_PROCURE_SUCCESS";
export const GET_ALL_PROCURE_FAILURE = "GET_ALL_PROCURE_FAILURE";

export const EMPTY_PROCURE_LIST = "EMPTY_PROCURE_LIST";

export const GET_RECORDS_REQUEST = "GET_RECORDS_REQUEST";
export const GET_RECORDS_SUCCESS = "GET_RECORDS_SUCCESS";
export const GET_RECORDS_FAILURE = "GET_RECORDS_FAILURE";

export const HANDLE_PROCURE_ORDER_MODAL = "HANDLE_PROCURE_ORDER_MODAL";

export const UPDATE_PROCURES_REQUEST = "UPDATE_PROCURES_REQUEST";
export const UPDATE_PROCURES_SUCCESS = "UPDATE_PROCURES_SUCCESS";
export const UPDATE_PROCURES_FAILURE = "UPDATE_PROCURES_FAILURE";