
export const SET_PROCRE_VIEW_TYPE = "SET_PROCRE_VIEW_TYPE";

export const GET_ALL_PROCURE_REQUEST =
  "GET_ALL_PROCURE_REQUEST";
export const GET_ALL_PROCURE_SUCCESS =
  "GET_ALL_PROCURE_SUCCESS";
export const GET_ALL_PROCURE_FAILURE =
  "GET_ALL_PROCURE_FAILURE";

