export const SET_PROCRE_VIEW_TYPE = "SET_PROCRE_VIEW_TYPE";

export const GET_ALL_PROCURE_REQUEST = "GET_ALL_PROCURE_REQUEST";
export const GET_ALL_PROCURE_SUCCESS = "GET_ALL_PROCURE_SUCCESS";
export const GET_ALL_PROCURE_FAILURE = "GET_ALL_PROCURE_FAILURE";

export const EMPTY_PROCURE_LIST = "EMPTY_PROCURE_LIST";

export const GET_RECORDS_REQUEST = "GET_RECORDS_REQUEST";
export const GET_RECORDS_SUCCESS = "GET_RECORDS_SUCCESS";
export const GET_RECORDS_FAILURE = "GET_RECORDS_FAILURE";

export const HANDLE_PROCURE_ORDER_MODAL = "HANDLE_PROCURE_ORDER_MODAL";

export const UPDATE_PROCURES_REQUEST = "UPDATE_PROCURES_REQUEST";
export const UPDATE_PROCURES_SUCCESS = "UPDATE_PROCURES_SUCCESS";
export const UPDATE_PROCURES_FAILURE = "UPDATE_PROCURES_FAILURE";

export const HANDLE_PRCURE_NOTES_DRAWER_MODAL = "HANDLE_PRCURE_NOTES_DRAWER_MODAL";

export const ADD_PROCURE_NOTES_REQUEST = "ADD_PROCURE_NOTES_REQUEST";
export const ADD_PROCURE_NOTES_SUCCESS = "ADD_PROCURE_NOTES_SUCCESS";
export const ADD_PROCURE_NOTES_FAILURE = "ADD_PROCURE_NOTES_FAILURE";

export const GET_NOTES_LIST_BY_PROCURE_ID_REQUEST =
  "GET_NOTES_LIST_BY_PROCURE_ID_REQUEST";
export const GET_NOTES_LIST_BY_PROCURE_ID_SUCCESS =
  "GET_NOTES_LIST_BY_PROCURE_ID_SUCCESS";
export const GET_NOTES_LIST_BY_PROCURE_ID_FAILURE =
  "GET_NOTES_LIST_BY_PROCURE_ID_FAILURE";

  export const PROCURE_TO_ACCEPTED_REQUEST =
  "PROCURE_TO_ACCEPTED_REQUEST";
  export const PROCURE_TO_ACCEPTED_SUCCESS =
  "PROCURE_TO_ACCEPTED_SUCCESS";
  export const PROCURE_TO_ACCEPTED_FAILURE =
  "PROCURE_TO_ACCEPTED_FAILURE"; 