export const SET_CLUB_VIEW_TYPE = "SET_CLUB_VIEW_TYPE";

export const GET_CLUB_ALLLIST_REQUEST = "GET_CLUB_ALLLIST_REQUEST";
export const GET_CLUB_ALLLIST_SUCCESS = "GET_CLUB_ALLLIST_SUCCESS";
export const GET_CLUB_ALLLIST_FAILURE = "GET_CLUB_ALLLIST_FAILURE";