export const SET_REGIONAL_DASH_VIEW_TYPE = "SET_REGIONAL_DASH_VIEW_TYPE";

export const HANDLE_SALES_MODAL = "HANDLE_SALES_MODAL";

export const CHANGE_SELECTED_REGIONAL_TIME_INTERVAL_REPORT =
  "CHANGE_SELECTED_REGIONAL_TIME_INTERVAL_REPORT";
// export const GET_CO2_TABLE_VIEW_REQUEST = "GET_CO2_TABLE_VIEW_REQUEST";
// export const GET_CO2_TABLE_VIEW_SUCCESS = "GET_CO2_TABLE_VIEW_SUCCESS";
// export const GET_CO2_TABLE_VIEW_FAILURE = "GET_CO2_TABLE_VIEW_FAILURE";




