
export const HANDLE_CREATE_SUBSCRIPTION_DRAWER="HANDLE_CREATE_SUBSCRIPTION_DRAWER";


export const UPDATE_SUSCRIPTION_REQUEST = "UPDATE_SUSCRIPTION_REQUEST";
export const UPDATE_SUSCRIPTION_SUCCESS = "UPDATE_SUSCRIPTION_SUCCESS";
export const UPDATE_SUSCRIPTION_FAILURE = "UPDATE_SUSCRIPTION_FAILURE";


export const GET_SUSCRIPTION_REQUEST =
  "GET_SUSCRIPTION_REQUEST";
export const GET_SUSCRIPTION_SUCCESS =
  "GET_SUSCRIPTION_SUCCESS";
export const GET_SUSCRIPTION_FAILURE =
  "GET_SUSCRIPTION_FAILURE";