export const HANDLE_CREATE_SUBSCRIPTION_DRAWER =
  "HANDLE_CREATE_SUBSCRIPTION_DRAWER";

export const UPDATE_SUSCRIPTION_REQUEST = "UPDATE_SUSCRIPTION_REQUEST";
export const UPDATE_SUSCRIPTION_SUCCESS = "UPDATE_SUSCRIPTION_SUCCESS";
export const UPDATE_SUSCRIPTION_FAILURE = "UPDATE_SUSCRIPTION_FAILURE";
export const GET_SUBSCRIPTIONS_REQUEST = "GET_SUBSCRIPTIONS_REQUEST";
export const GET_SUBSCRIPTIONS_SUCCESS = "GET_SUBSCRIPTIONS_SUCCESS";
export const GET_SUBSCRIPTIONS_FAILURE = "GET_SUBSCRIPTIONS_FAILURE";

export const GET_SUSCRIPTION_REQUEST = "GET_SUSCRIPTION_REQUEST";
export const GET_SUSCRIPTION_SUCCESS = "GET_SUSCRIPTION_SUCCESS";
export const GET_SUSCRIPTION_FAILURE = "GET_SUSCRIPTION_FAILURE";

export const ADD_NEW_SUBSCRIPTION_REQUEST = "ADD_NEW_SUBSCRIPTION_REQUEST";
export const ADD_NEW_SUBSCRIPTION_SUCCESS = "ADD_NEW_SUBSCRIPTION_SUCCESS";
export const ADD_NEW_SUBSCRIPTION_FAILURE = "ADD_NEW_SUBSCRIPTION_FAILURE";
export const GET_NEW_SUBSCRIPTION_REQUEST = "GET_NEW_SUBSCRIPTION_REQUEST";
export const GET_NEW_SUBSCRIPTION_SUCCESS = "GET_NEW_SUBSCRIPTION_SUCCESS";
export const GET_NEW_SUBSCRIPTION_FAILURE = "GET_NEW_SUBSCRIPTION_FAILURE";


export const HANDLE_SUSCRIPTION_MODAL = "HANDLE_SUSCRIPTION_MODAL";

export const ADD_SUSCRIPTIONS_REQUEST = "ADD_SUSCRIPTIONS_REQUEST";
export const ADD_SUSCRIPTIONS_SUCCESS = "ADD_SUSCRIPTIONS_SUCCESS";
export const ADD_SUSCRIPTIONS_FAILURE = "ADD_SUSCRIPTIONS_FAILURE";
