export const GET_DEVELOPMENT_REQUEST = "GET_DEVELOPMENT_REQUEST";
export const GET_DEVELOPMENT_SUCCESS = "GET_DEVELOPMENT_SUCCESS";
export const GET_DEVELOPMENT_FAILURE = "GET_DEVELOPMENT_FAILURE";



export const ADD_DEVELOPMENT_REQUEST = "ADD_DEVELOPMENT_REQUEST";
export const ADD_DEVELOPMENT_SUCCESS = "ADD_DEVELOPMENT_SUCCESS";
export const ADD_DEVELOPMENT_FAILURE = "ADD_DEVELOPMENT_FAILURE";


export const UPDATE_DEVELOPMENT_REQUEST = "UPDATE_DEVELOPMENT_REQUEST";
export const UPDATE_DEVELOPMENT_SUCCESS = "UPDATE_DEVELOPMENT_SUCCESS";
export const UPDATE_DEVELOPMENT_FAILURE = "UPDATE_DEVELOPMENT_FAILURE";

export const GET_DEVELOPMENT_SEARCH_REQUEST="GET_DEVELOPMENT_SEARCH_REQUEST";
export const GET_DEVELOPMENT_SEARCH_SUCCESS="GET_DEVELOPMENT_SEARCH_SUCCESS";
export const GET_DEVELOPMENT_SEARCH_FAILURE="GET_DEVELOPMENT_SEARCH_FAILURE";

export const REMOVE_DEVELOPMENT_REQUEST = "REMOVE_DEVELOPMENT_REQUEST";
export const REMOVE_DEVELOPMENT_SUCCESS = "REMOVE_DEVELOPMENT_SUCCESS";
export const REMOVE_DEVELOPMENT_FAILURE = "REMOVE_DEVELOPMENT_FAILURE";



export const HANDLE_CLAER_REDUCER_DATA_DEVELOPMENT = "HANDLE_CLAER_REDUCER_DATA_DEVELOPMENT";


export const GET_DEVELOPMENT_COUNT_REQUEST = "GET_DEVELOPMENT_COUNT_REQUEST";
export const GET_DEVELOPMENT_COUNT_SUCCESS = "GET_DEVELOPMENT_COUNT_SUCCESS";
export const GET_DEVELOPMENT_COUNT_FAILURE = "GET_DEVELOPMENT_COUNT_FAILURE";





