export const GET_MASTER_KPI_REQUEST = "GET_MASTER_KPI_REQUEST";
export const GET_MASTER_KPI_SUCCESS = "GET_MASTER_KPI_SUCCESS";
export const GET_MASTER_KPI_FAILURE = "GET_MASTER_KPI_FAILURE";

export const ADD_MASTER_KPI_REQUEST = "ADD_MASTER_KPI_REQUEST";
export const ADD_MASTER_KPI_SUCCESS = "ADD_MASTER_KPI_SUCCESS";
export const ADD_MASTER_KPI_FAILURE = "ADD_MASTER_KPI_FAILURE";

export const REMOVE_MASTER_KPI_REQUEST = "REMOVE_MASTER_KPI_REQUEST";
export const REMOVE_MASTER_KPI_SUCCESS = "REMOVE_MASTER_KPI_SUCCESS";
export const REMOVE_MASTER_KPI_FAILURE = "REMOVE_MASTER_KPI_FAILURE";

export const UPDATE_MASTER_KPI_REQUEST = "UPDATE_MASTER_KPI_REQUEST";
export const UPDATE_MASTER_KPI_SUCCESS = "UPDATE_MASTER_KPI_SUCCESS";
export const UPDATE_MASTER_KPI_FAILURE = "UPDATE_MASTER_KPI_FAILURE";

export const GET_MASTER_KPI_SEARCH_REQUEST="GET_MASTER_KPI_SEARCH_REQUEST";
export const GET_MASTER_KPI_SEARCH_SUCCESS="GET_MASTER_KPI_SEARCH_SUCCESS";
export const GET_MASTER_KPI_SEARCH_FAILURE="GET_MASTER_KPI_SEARCH_FAILURE";

export const HANDLE_CLAER_REDUCER_DATA_MASTER_KPI = "HANDLE_CLAER_REDUCER_DATA_MASTER_KPI";


export const GET_MASTER_KPI_COUNT_REQUEST = "GET_MASTER_KPI_COUNT_REQUEST";
export const GET_MASTER_KPI_COUNT_SUCCESS = "GET_MASTER_KPI_COUNT_SUCCESS";
export const GET_MASTER_KPI_COUNT_FAILURE = "GET_MASTER_KPI_COUNT_FAILURE";


export const LINK_MASTER_CURRENCY_TOGGLE_REQUEST =
  "LINK_MASTER_CURRENCY_TOGGLE_REQUEST";
export const LINK_MASTER_CURRENCY_TOGGLE_SUCCESS =
  "LINK_MASTER_CURRENCY_TOGGLE_SUCCESS";
export const LINK_MASTER_CURRENCY_TOGGLE_FAILURE =
  "LINK_MASTER_CURRENCY_TOGGLE_FAILURE";



