export const ADD_ACTIVITY_CALL_REQUEST = "ADD_ACTIVITY_CALL_REQUEST";
export const ADD_ACTIVITY_CALL_SUCCESS = "ADD_ACTIVITY_CALL_SUCCESS";
export const ADD_ACTIVITY_CALL_FAILURE = "ADD_ACTIVITY_CALL_FAILURE";





export const ADD_ACTIVITY_EVENT_REQUEST = "ADD_ACTIVITY_EVENT_REQUEST";
export const ADD_ACTIVITY_EVENT_SUCCESS = "ADD_ACTIVITY_EVENT_SUCCESS";
export const ADD_ACTIVITY_EVENT_FAILURE = "ADD_ACTIVITY_EVENT_FAILURE";




export const ADD_ACTIVITY_TASK_REQUEST = "ADD_ACTIVITY_TASK_REQUEST";
export const ADD_ACTIVITY_TASK_SUCCESS = "ADD_ACTIVITY_TASK_SUCCESS";
export const ADD_ACTIVITY_TASK_FAILURE = "ADD_ACTIVITY_TASK_FAILURE";

export const GET_ACTIVITY_TIMELINE_REQUEST = "GET_ACTIVITY_TIMELINE_REQUEST";
export const GET_ACTIVITY_TIMELINE_SUCCESS = "GET_ACTIVITY_TIMELINE_SUCCESS";
export const GET_ACTIVITY_TIMELINE_FAILURE = "GET_ACTIVITY_TIMELINE_FAILURE";


export const HANDLE_CALL_ACTIVITY_MODAL = "HANDLE_CALL_ACTIVITY_MODAL";



export const ADD_EVENT_LOCATION_REQUEST = "ADD_EVENT_LOCATION_REQUEST";
export const ADD_EVENT_LOCATION_SUCCESS = "ADD_EVENT_LOCATION_SUCCESS";
export const ADD_EVENT_LOCATION_FAILURE = "ADD_EVENT_LOCATION_FAILURE";